[advisories]
vulnerability = "deny"
unmaintained = "transitive"
yanked = "warn"
notice = "warn"

[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0"]
default = "deny"

[bans]
multiple-versions = "deny"
highlight = "all"
